server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/enterprise_bbs
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.bbs.entity
  configuration:
    map-underscore-to-camel-case: true
