server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bbs_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 3MB

bbs:
  upload-root: ${user.dir}/uploads

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.feiyang.bbs.entity
  configuration:
    map-underscore-to-camel-case: true
